# File: .github/workflows/python_tests.yml

name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: python -m unittest discover
    - name: Install Dependencies
      run: |
        set -e
        python -m pip install --upgrade pip
        pip install -r requirements.txt
